INSERT INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('WEAPON_PISTOL_AMMO', 'Pistol Ammo', 1, 0, 1, 10);
INSERT INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('WEAPON_APPISTOL_AMMO', 'APPistol Ammo', 1, 0, 1, 10);
INSERT INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('WEAPON_SMG_AMMO', 'Smg Ammo', 1, 0, 1, 10);
INSERT INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('WEAPON_ADVANCEDRIFLE_AMMO', 'Advanced Rifle Ammo', 1, 0, 1, 10);
INSERT INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('WEAPON_ASSAULTRIFLE_AMMO', 'Assualt Rifle Ammo', 1, 0, 1, 10);
INSERT INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('WEAPON_ASSAULTSHOTGUN_AMMO', 'Assualt Shotgun Ammo', 1, 0, 1, 10);
INSERT INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('WEAPON_ASSAULTSMG_AMMO', 'Assault Smg Ammo', 1, 0, 1, 10);
INSERT INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('WEAPON_AUTOSHOTGUN_AMMO', 'AutoShotgun Ammo', 1, 0, 1, 10);
INSERT INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('WEAPON_CARBINERIFLE_AMMO', 'Carbine Rifle Ammo', 1, 0, 1, 10);
INSERT INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('WEAPON_COMBATPISTOL_AMMO', 'Combat Pistol Ammo', 1, 0, 1, 10);
INSERT INTO essentialmode.items (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('WEAPON_PUMPSHOTGUN_AMMO', 'Pump Shotgun Ammo', 1, 0, 1, 10);
